import type { Metadata } from "next";
import "@/styles/globals.css";
import { ThemeProvider } from "@/components/global/Provider";
import { Inter, DynaPuff } from "next/font/google";
import CursorEffect from "@/components/ui/CursorEffect";
import { Toaster } from 'sonner';
import ConvexClientProvider from "@/components/global/ConvexClientProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const dynaPuff = DynaPuff({
  subsets: ["latin"],
  variable: "--font-dynapuff",
  display: "swap",
  preload: true,
});

// Metadata needs to be exported from a server component
export const metadata: Metadata = {
  title: "SamCux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${inter.variable} ${dynaPuff.variable}`}>
      <body className="antialiased bg-sa-light-bg text-sa-light-accent dark:bg-sa-dark-bg dark:text-sa-dark-text-main">
        <ConvexClientProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
            <CursorEffect />
          </ThemeProvider>
        </ConvexClientProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
